#!/bin/sh

die() {
	echo
	echo "error: $1";
	echo
	exit -1;
}

echo

echo -n "running autoheader..."
autoheader
if [ "$?" != "0" ]; then die "running autoheader"; fi
echo "done"

echo -n "running aclocal..."
if test -r acinclude.m4; then
   touch acinclude.m4
   aclocal
else
   aclocal -I rtai-core/config/autoconf
fi
if [ "$?" != "0" ]; then die "running aclocal"; fi
echo "done"

echo -n "running autoconf..."
autoconf
if [ "$?" != "0" ]; then die "running autoconf"; fi
echo "done"

echo -n "running automake..."
automake
if [ "$?" != "0" ]; then die "running automake"; fi
echo "done"

echo
